### ISSUE TITLE
[ZEON] - recommended additions

### ISSUE THREAD

**Issue by zeon-neon** [NeonGamerBot-QK/zeon#1]
# Meta

- [ ] Your default branch is not 'main' please update it.

- [ ] Your repo does not have web commit signing off enabled. **PLEASE ENABLE IT**
# Automation

- [x] **Mark this to override & close this issue.**
