### ISSUE TITLE
[ZEON] - recommended additions

### ISSUE THREAD

**Issue by zeon-neon** [NeonGamerBot-QK/zeon#2]
# Meta

- [ ] Your default branch is not 'main' please update it. [enable here](https://github.com/NeonGamerBot-QK/zeon/settings)

- [ ] Your repo does not have web commit signing off enabled. **PLEASE ENABLE IT** [here](https://github.com/NeonGamerBot-QK/zeon/settings)

- [ ] This repo does not have discussions enabled

- [ ] This repo does not have a code of conduct (feature is in beta!)

- [ ] undefined
# Automation

- [ ] **Mark this to override & close this issue.**
